const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const ERROR_CONFLICT = 409;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  ERROR_CONFLICT,
  ERROR_UNAUTHORIZED,
  ERROR_FORBIDDEN,
};
